# Generated by Django 4.1.4 on 2023-01-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0009_alter_classe_options_alter_eleve_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='dateNaisElev',
            field=models.DateField(default='1995-12-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleve',
            name='genreElev',
            field=models.CharField(default='Masculin', max_length=200),
            preserve_default=False,
        ),
    ]
