# Generated by Django 4.1.4 on 2023-01-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0010_eleve_datenaiselev_eleve_genreelev'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='AdresseElev',
            field=models.CharField(default='rue 445, Douala', max_length=200),
        ),
        migrations.AddField(
            model_name='matiere',
            name='coeffMat',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='classe',
            name='typClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOOLAPP.type'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ProfMat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOOLAPP.professeur'),
        ),
    ]
