# Generated by Django 4.1.4 on 2023-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0011_eleve_adresseelev_matiere_coeffmat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='AdresseProf',
            field=models.CharField(default='rue 445, Douala', max_length=200),
        ),
        migrations.AddField(
            model_name='professeur',
            name='DateJoinProf',
            field=models.DateField(default='2021-10-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='DesignationProf',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='MatpossibProf',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='Username',
            field=models.CharField(default='matador', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='dateNaisProf',
            field=models.DateField(default='1985-10-5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='genreProf',
            field=models.CharField(default='Masculin', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professeur',
            name='password',
            field=models.CharField(default='12340', max_length=10),
            preserve_default=False,
        ),
    ]
