# Generated by Django 4.1.4 on 2023-01-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0012_professeur_adresseprof_professeur_datejoinprof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='typClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOOLAPP.type'),
        ),
    ]
