# Generated by Django 4.1.4 on 2023-01-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0013_alter_classe_typclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='typClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOOLAPP.type'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ClassMat',
            field=models.ManyToManyField(blank=True, null=True, to='SCOOLAPP.classe'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ProfMat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOOLAPP.professeur'),
        ),
    ]
