# Generated by Django 4.1.4 on 2023-01-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0014_alter_classe_typclass_alter_matiere_classmat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='DescrptProf',
            field=models.CharField(default='Rien par rapport !', max_length=400),
        ),
    ]
