# Generated by Django 4.1.4 on 2023-01-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0016_matiere_descrptmat_matiere_photomat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='photoMat',
        ),
    ]
