# Generated by Django 4.1.4 on 2023-01-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0017_remove_matiere_photomat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeNote', models.CharField(max_length=200)),
                ('valeurNote', models.IntegerField()),
                ('state', models.BooleanField(default=False)),
                ('eleveNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.eleve')),
                ('matierNote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.matiere')),
            ],
            options={
                'ordering': ['eleveNote'],
            },
        ),
    ]
