# Generated by Django 4.1.4 on 2023-01-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0018_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='matierNote',
            new_name='matiereNote',
        ),
    ]
