# Generated by Django 4.1.4 on 2023-01-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0019_rename_matiernote_note_matierenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='codeClass',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='MatriculeElev',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='codeNote',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='professeur',
            name='MatriculeProf',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='CodeTyp',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
