# Generated by Django 4.1.4 on 2023-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0020_alter_classe_codeclass_alter_eleve_matriculeelev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='CodeMat',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
