# Generated by Django 4.1.4 on 2023-01-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0021_alter_matiere_codemat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='codeNote',
        ),
    ]
