# Generated by Django 4.1.4 on 2023-01-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0023_note_codenote_alter_classe_codeclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='codeNote',
        ),
    ]
