# Generated by Django 4.1.4 on 2023-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0024_remove_note_codenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='groupeMat',
            field=models.CharField(default='Groupe A', max_length=10),
        ),
        migrations.AddField(
            model_name='note',
            name='CommentNote',
            field=models.CharField(default='Pas de commentaires à faire', max_length=200),
        ),
    ]
