# Generated by Django 4.1.4 on 2023-01-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0025_matiere_groupemat_note_commentnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeGroup', models.CharField(default='TYP-', max_length=100, unique=True)),
                ('nomGroup', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='groupeMat',
        ),
        migrations.AddField(
            model_name='matiere',
            name='groupMat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SCOOLAPP.groupe'),
        ),
    ]
