# Generated by Django 4.1.4 on 2023-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0026_groupe_remove_matiere_groupemat_matiere_groupmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='SurnomMat',
            field=models.CharField(default='l', max_length=300),
            preserve_default=False,
        ),
    ]
