# Generated by Django 4.1.4 on 2023-01-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0028_remove_groupe_codegroup_alter_groupe_nomgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinDeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.eleve')),
            ],
            options={
                'ordering': ['eleve'],
            },
        ),
    ]
