# Generated by Django 4.1.4 on 2023-01-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0029_bulletindenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindenote',
            name='classe',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.classe'),
            preserve_default=False,
        ),
    ]
