# Generated by Django 4.1.4 on 2023-01-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0030_bulletindenote_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindenote',
            name='MoyG',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
