# Generated by Django 4.1.4 on 2023-01-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0031_bulletindenote_moyg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletindenote',
            name='classe',
        ),
    ]
