# Generated by Django 4.1.4 on 2023-01-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0033_alter_bulletindenote_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindenote',
            name='ficheWordModel',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
