# Generated by Django 4.1.4 on 2023-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0034_bulletindenote_fichewordmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletindenote',
            name='ficheWordModel',
        ),
        migrations.AddField(
            model_name='bulletindenote',
            name='ficheWordE',
            field=models.FileField(default=1, upload_to='BulletinsEleves/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='ficheWordModel',
            field=models.FileField(default=1, upload_to='ModelBulletinsClasse/'),
            preserve_default=False,
        ),
    ]
