# Generated by Django 4.1.4 on 2023-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0035_remove_bulletindenote_fichewordmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletindenote',
            name='Rang',
            field=models.CharField(default='not defined', max_length=10),
        ),
        migrations.AddField(
            model_name='bulletindenote',
            name='RangGA',
            field=models.CharField(default='not defined', max_length=10),
        ),
        migrations.AddField(
            model_name='bulletindenote',
            name='RangGB',
            field=models.CharField(default='not defined', max_length=10),
        ),
        migrations.AddField(
            model_name='bulletindenote',
            name='RangGC',
            field=models.CharField(default='not defined', max_length=10),
        ),
    ]
