# Generated by Django 4.1.4 on 2023-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0036_bulletindenote_rang_bulletindenote_rangga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAdmin', models.CharField(max_length=300)),
                ('prenomAdmin', models.CharField(max_length=300)),
                ('MatriculeAdmin', models.CharField(default='PROF-', max_length=200, unique=True)),
                ('TelephoneAdmin', models.CharField(max_length=20)),
                ('EmailAdmin', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('genreAdmin', models.CharField(max_length=200)),
                ('dateNaisAdmin', models.DateField()),
                ('AdresseAdmin', models.CharField(default='rue 445, Douala', max_length=200)),
                ('DescrptAdmin', models.CharField(default='Rien par rapport !', max_length=400)),
                ('photoAdmin', models.ImageField(upload_to='photosProfs/')),
            ],
            options={
                'ordering': ['nomAdmin', 'prenomAdmin'],
            },
        ),
    ]
