# Generated by Django 4.1.4 on 2023-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0037_administrateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='MatriculeAdmin',
            field=models.CharField(default='ADMIN-', max_length=200, unique=True),
        ),
    ]
