# Generated by Django 4.1.4 on 2023-02-01 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SCOOLAPP', '0038_alter_administrateur_matriculeadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='state',
        ),
        migrations.RemoveField(
            model_name='note',
            name='state',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='state',
        ),
        migrations.AlterField(
            model_name='bulletindenote',
            name='Rang',
            field=models.CharField(default='not defined', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='bulletindenote',
            name='RangGA',
            field=models.CharField(default='not defined', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='bulletindenote',
            name='RangGB',
            field=models.CharField(default='not defined', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='bulletindenote',
            name='RangGC',
            field=models.CharField(default='not defined', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='bulletindenote',
            name='eleve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SCOOLAPP.eleve'),
        ),
        migrations.AlterField(
            model_name='bulletindenote',
            name='ficheWordE',
            field=models.FileField(editable=False, upload_to='BulletinsEleves/'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ClassMat',
            field=models.ManyToManyField(blank=True, to='SCOOLAPP.classe'),
        ),
    ]
